import pathlib

path = pathlib.Path("phone-app/design.js")
content = path.read_text()


def apply(old, new, label):
    global content
    count = content.count(old)
    if count != 1:
        raise SystemExit(f"ABORT: expected exactly 1 match for '{label}', found {count}. No changes written.")
    content = content.replace(old, new)
    print(f"OK: patched '{label}'")


# 1) Give pinned reference/material photos their own gallery on the print
# sheet, right after Plants -- same card style, so they "pop up" the same
# way plant photos already do.
apply(
    "  if (headCounts.size) {\n"
    "    html += `<div class=\"design-print-section\"><h3>Sprinkler heads</h3>`;",
    "  const photoEls = elements.filter((e) => e.type === 'photo' && e.src);\n"
    "  if (photoEls.length) {\n"
    "    html += `<div class=\"design-print-section\"><h3>Materials / reference photos</h3><div class=\"design-print-plant-grid\">`;\n"
    "    for (const p of photoEls) {\n"
    "      html += `\n"
    "        <div class=\"design-print-plant-card\">\n"
    "          <img class=\"design-print-plant-photo\" src=\"${p.src}\" alt=\"${escapeHtml(p.caption || 'Reference photo')}\" />\n"
    "          <div class=\"design-print-plant-name\">${escapeHtml(p.caption || 'Reference photo')}</div>\n"
    "        </div>`;\n"
    "    }\n"
    "    html += `</div></div>`;\n"
    "  }\n"
    "\n"
    "  if (headCounts.size) {\n"
    "    html += `<div class=\"design-print-section\"><h3>Sprinkler heads</h3>`;",
    "add Materials/reference-photos gallery to the print sheet",
)

# 2) Replace the Download PNG/PDF handlers. The first version of this feature
# rendered just the bare Konva plan (PNG) or the plan plus a plain text list
# (PDF) -- this rebuilds both from the *same* #design-print-sheet HTML that
# Print already uses (via html2canvas), so what you download matches what
# Print shows: title, plan with photo pins, Site areas, Plants gallery,
# Materials gallery, etc. The PDF paginates using each section/card/row's
# real on-screen edges as safe cut points, so nothing gets sliced in half.
apply(
    "document.getElementById('btn-design-download-png').addEventListener('click', () => {\n"
    "  if (!currentDesign || !stage) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => {\n"
    "    const a = document.createElement('a');\n"
    "    a.href = stage.toDataURL({ pixelRatio: 2 });\n"
    "    a.download = `${designFileBaseName()}.png`;\n"
    "    document.body.appendChild(a);\n"
    "    a.click();\n"
    "    a.remove();\n"
    "  }, 150);\n"
    "});\n"
    "\n"
    "document.getElementById('btn-design-download-pdf').addEventListener('click', () => {\n"
    "  if (!currentDesign || !stage) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => {\n"
    "    const { jsPDF } = window.jspdf;\n"
    "    const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'letter' });\n"
    "    const pageW = doc.internal.pageSize.getWidth();\n"
    "    const pageH = doc.internal.pageSize.getHeight();\n"
    "    const margin = 36;\n"
    "\n"
    "    const linkBits = [];\n"
    "    if (currentDesign.customers && currentDesign.customers.name) linkBits.push(currentDesign.customers.name);\n"
    "    if (currentDesign.jobs && currentDesign.jobs.title) linkBits.push(currentDesign.jobs.title);\n"
    "\n"
    "    doc.setFontSize(18);\n"
    "    doc.text(currentDesign.name || 'Untitled design', margin, margin);\n"
    "    doc.setFontSize(10);\n"
    "    doc.setTextColor(90);\n"
    "    const metaLine = `${linkBits.length ? linkBits.join(' \\u2014 ') + '   ' : ''}Printed ${new Date().toLocaleDateString()}   Scale: 1 ft \\u2248 ${pxPerFt.toFixed(1)} px`;\n"
    "    doc.text(metaLine, margin, margin + 16);\n"
    "\n"
    "    const imgData = stage.toDataURL({ pixelRatio: 2 });\n"
    "    const imgProps = doc.getImageProperties(imgData);\n"
    "    const maxW = pageW - margin * 2;\n"
    "    const maxH = pageH - margin - 50;\n"
    "    let drawW = maxW;\n"
    "    let drawH = (imgProps.height / imgProps.width) * drawW;\n"
    "    if (drawH > maxH) {\n"
    "      drawH = maxH;\n"
    "      drawW = (imgProps.width / imgProps.height) * drawH;\n"
    "    }\n"
    "    doc.addImage(imgData, 'PNG', margin, margin + 30, drawW, drawH);\n"
    "\n"
    "    doc.addPage();\n"
    "    let y = margin;\n"
    "    doc.setTextColor(0);\n"
    "    function heading(text) {\n"
    "      if (y > pageH - margin - 20) { doc.addPage(); y = margin; }\n"
    "      doc.setFontSize(13);\n"
    "      doc.setFont(undefined, 'bold');\n"
    "      doc.text(text, margin, y);\n"
    "      y += 18;\n"
    "      doc.setFont(undefined, 'normal');\n"
    "      doc.setFontSize(10);\n"
    "    }\n"
    "    function row(label, value) {\n"
    "      if (y > pageH - margin) { doc.addPage(); y = margin; }\n"
    "      doc.text(String(label), margin, y);\n"
    "      doc.text(String(value), pageW - margin, y, { align: 'right' });\n"
    "      y += 14;\n"
    "    }\n"
    "\n"
    "    const plantCounts = new Map();\n"
    "    elements.filter((e) => e.type === 'plant').forEach((e) => plantCounts.set(e.plantKey, (plantCounts.get(e.plantKey) || 0) + 1));\n"
    "    const headEls = elements.filter((e) => e.type === 'head');\n"
    "    const headCounts = new Map();\n"
    "    headEls.forEach((e) => headCounts.set(e.headKey, (headCounts.get(e.headKey) || 0) + 1));\n"
    "    const zoneEls = elements.filter((e) => e.type === 'zone').sort((a, b) => a.zoneNumber - b.zoneNumber);\n"
    "    const pipeEls = elements.filter((e) => e.type === 'pipe');\n"
    "    const lateralFt = pipeEls.filter((e) => e.subtype === 'lateral').reduce((s, e) => s + polylineLengthFt(e.points), 0);\n"
    "    const mainlineFt = pipeEls.filter((e) => e.subtype === 'mainline').reduce((s, e) => s + polylineLengthFt(e.points), 0);\n"
    "    const fixtureCounts = new Map();\n"
    "    elements.filter((e) => e.type === 'fixture').forEach((e) => fixtureCounts.set(e.fixtureKey, (fixtureCounts.get(e.fixtureKey) || 0) + 1));\n"
    "    const areaTotals = {};\n"
    "    elements.filter((e) => e.type === 'area' && e.subtype !== 'boundary').forEach((e) => {\n"
    "      areaTotals[e.subtype] = (areaTotals[e.subtype] || 0) + polygonAreaSqFt(e.points);\n"
    "    });\n"
    "\n"
    "    heading('Site areas');\n"
    "    if (Object.keys(areaTotals).length === 0) row('No areas drawn', '');\n"
    "    for (const key of Object.keys(areaTotals)) {\n"
    "      const preset = CAT.AREA_PRESETS.find((p) => p.key === key);\n"
    "      row(preset ? preset.name : key, `${areaTotals[key].toFixed(0)} sq ft`);\n"
    "    }\n"
    "\n"
    "    if (plantCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Plants');\n"
    "      for (const [key, count] of plantCounts) {\n"
    "        const p = CAT.PLANT_CATALOG.find((x) => x.key === key);\n"
    "        row(p ? p.name : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (headCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Sprinkler heads');\n"
    "      for (const [key, count] of headCounts) {\n"
    "        const h = CAT.HEAD_CATALOG.find((x) => x.key === key);\n"
    "        row(h ? `${h.brand} ${h.model}` : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (zoneEls.length) {\n"
    "      y += 6;\n"
    "      heading('Zones');\n"
    "      for (const z of zoneEls) {\n"
    "        const heads = headEls.filter((h) => h.zoneNumber === z.zoneNumber);\n"
    "        const gpm = heads.reduce((s, h) => {\n"
    "          const h2 = CAT.HEAD_CATALOG.find((x) => x.key === h.headKey);\n"
    "          return s + (h2 ? h2.gpmFull : 0) * ((h.arc || 360) / 360);\n"
    "        }, 0);\n"
    "        row(`Zone ${z.zoneNumber}${z.label ? ` (${z.label})` : ''}`, `${heads.length} heads, ~${gpm.toFixed(1)} GPM`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (mainlineFt || lateralFt) {\n"
    "      y += 6;\n"
    "      heading('Pipe (approx.)');\n"
    "      row('Mainline', `${mainlineFt.toFixed(0)} ft`);\n"
    "      row('Lateral', `${lateralFt.toFixed(0)} ft`);\n"
    "    }\n"
    "\n"
    "    if (fixtureCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Fixtures');\n"
    "      for (const [key, count] of fixtureCounts) {\n"
    "        const f = CAT.FIXTURE_CATALOG.find((x) => x.key === key);\n"
    "        row(f ? f.name : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    doc.save(`${designFileBaseName()}.pdf`);\n"
    "  }, 150);\n"
    "});",
    "const PRINT_RENDER_WIDTH_PX = 720;  // matches Letter width (8.5in) minus 0.5in margins each side, at 96px/in\n"
    "const PRINT_PAGE_HEIGHT_PX = 960;   // matches Letter height (11in) minus 0.5in margins top/bottom, at 96px/in\n"
    "\n"
    "function showPrintSheetForCapture() {\n"
    "  const box = document.getElementById('design-print-sheet');\n"
    "  box.classList.add('design-print-render-mode');\n"
    "  return box;\n"
    "}\n"
    "\n"
    "function hidePrintSheetAfterCapture() {\n"
    "  document.getElementById('design-print-sheet').classList.remove('design-print-render-mode');\n"
    "}\n"
    "\n"
    "function waitForImagesToLoad(container, timeoutMs) {\n"
    "  const imgs = Array.from(container.querySelectorAll('img'));\n"
    "  const timeout = timeoutMs || 8000;\n"
    "  return Promise.all(imgs.map((img) => {\n"
    "    if (img.complete) return Promise.resolve();\n"
    "    return new Promise((resolve) => {\n"
    "      const done = () => { img.removeEventListener('load', done); img.removeEventListener('error', done); resolve(); };\n"
    "      img.addEventListener('load', done);\n"
    "      img.addEventListener('error', done);\n"
    "      setTimeout(done, timeout);\n"
    "    });\n"
    "  }));\n"
    "}\n"
    "\n"
    "// Picks page-break Y coordinates that fall in the gaps between sections,\n"
    "// cards, and rows instead of naive fixed-height slicing, so a plant card\n"
    "// (or a photo card, or a table row) never gets cut in half across pages --\n"
    "// the same intent as the print stylesheet's `break-inside: avoid-page`.\n"
    "function computeSafePageBreaks(container, pageHeightPx) {\n"
    "  const blocks = Array.from(container.querySelectorAll('.design-print-section, .design-print-plant-card, .design-print-row, .design-print-plan'));\n"
    "  const containerTop = container.getBoundingClientRect().top;\n"
    "  const edges = blocks.map((el) => {\n"
    "    const r = el.getBoundingClientRect();\n"
    "    return { top: r.top - containerTop, bottom: r.bottom - containerTop };\n"
    "  });\n"
    "  const totalHeight = container.scrollHeight;\n"
    "  const breaks = [0];\n"
    "  let cursor = 0;\n"
    "  while (cursor + pageHeightPx < totalHeight) {\n"
    "    let candidate = cursor + pageHeightPx;\n"
    "    for (let iter = 0; iter < 5; iter++) {\n"
    "      let changed = false;\n"
    "      for (const e of edges) {\n"
    "        if (e.top < candidate && e.bottom > candidate && e.top > cursor + 20) {\n"
    "          candidate = e.top;\n"
    "          changed = true;\n"
    "        }\n"
    "      }\n"
    "      if (!changed) break;\n"
    "    }\n"
    "    if (candidate <= cursor) candidate = cursor + pageHeightPx;\n"
    "    breaks.push(candidate);\n"
    "    cursor = candidate;\n"
    "  }\n"
    "  breaks.push(totalHeight);\n"
    "  return breaks;\n"
    "}\n"
    "\n"
    "async function withCapturedPrintSheet(btn, fn) {\n"
    "  if (!currentDesign || !stage) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  const originalText = btn.textContent;\n"
    "  btn.textContent = 'Preparing\\u2026';\n"
    "  btn.disabled = true;\n"
    "  try {\n"
    "    await new Promise((resolve) => setTimeout(resolve, 150));\n"
    "    buildPrintSheet();\n"
    "    const box = showPrintSheetForCapture();\n"
    "    await waitForImagesToLoad(box);\n"
    "    const canvas = await html2canvas(box, { useCORS: true, backgroundColor: '#ffffff', scale: 2 });\n"
    "    const breaks = computeSafePageBreaks(box, PRINT_PAGE_HEIGHT_PX);\n"
    "    hidePrintSheetAfterCapture();\n"
    "    await fn(canvas, breaks);\n"
    "  } catch (err) {\n"
    "    hidePrintSheetAfterCapture();\n"
    "    alert('Could not generate the file: ' + err.message);\n"
    "  } finally {\n"
    "    btn.textContent = originalText;\n"
    "    btn.disabled = false;\n"
    "  }\n"
    "}\n"
    "\n"
    "document.getElementById('btn-design-download-png').addEventListener('click', () => {\n"
    "  const btn = document.getElementById('btn-design-download-png');\n"
    "  withCapturedPrintSheet(btn, async (canvas) => {\n"
    "    const a = document.createElement('a');\n"
    "    a.href = canvas.toDataURL('image/png');\n"
    "    a.download = `${designFileBaseName()}.png`;\n"
    "    document.body.appendChild(a);\n"
    "    a.click();\n"
    "    a.remove();\n"
    "  });\n"
    "});\n"
    "\n"
    "document.getElementById('btn-design-download-pdf').addEventListener('click', () => {\n"
    "  const btn = document.getElementById('btn-design-download-pdf');\n"
    "  withCapturedPrintSheet(btn, async (canvas, breaks) => {\n"
    "    const { jsPDF } = window.jspdf;\n"
    "    const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter' });\n"
    "    const marginPt = 36; // 0.5in, matching the print stylesheet's @page margin\n"
    "    const contentWidthPt = doc.internal.pageSize.getWidth() - marginPt * 2;\n"
    "    const scale = 2; // must match the html2canvas scale used to build `canvas`\n"
    "\n"
    "    for (let i = 0; i < breaks.length - 1; i++) {\n"
    "      const sliceTopPx = breaks[i] * scale;\n"
    "      const sliceHeightPx = (breaks[i + 1] - breaks[i]) * scale;\n"
    "      if (sliceHeightPx <= 0) continue;\n"
    "      const sliceCanvas = document.createElement('canvas');\n"
    "      sliceCanvas.width = canvas.width;\n"
    "      sliceCanvas.height = sliceHeightPx;\n"
    "      const ctx = sliceCanvas.getContext('2d');\n"
    "      ctx.fillStyle = '#ffffff';\n"
    "      ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);\n"
    "      ctx.drawImage(canvas, 0, sliceTopPx, canvas.width, sliceHeightPx, 0, 0, canvas.width, sliceHeightPx);\n"
    "      // JPEG, not PNG -- this is a photo-heavy report, and lossless PNG at 2x\n"
    "      // scale made multi-page PDFs 10-15MB+. JPEG at 0.85 quality looks the\n"
    "      // same to the eye and comes in at a fraction of the size.\n"
    "      const sliceDataUrl = sliceCanvas.toDataURL('image/jpeg', 0.85);\n"
    "      const sliceHeightPt = (sliceHeightPx / canvas.width) * contentWidthPt;\n"
    "      if (i > 0) doc.addPage();\n"
    "      doc.addImage(sliceDataUrl, 'JPEG', marginPt, marginPt, contentWidthPt, sliceHeightPt);\n"
    "    }\n"
    "\n"
    "    doc.save(`${designFileBaseName()}.pdf`);\n"
    "  });\n"
    "});",
    "replace Download PNG/PDF with html2canvas-based print-sheet capture",
)

path.write_text(content)
print("DONE: phone-app/design.js patched successfully.")
