import pathlib

path = pathlib.Path("phone-app/design.js")
content = path.read_text()


def apply(old, new, label):
    global content
    count = content.count(old)
    if count != 1:
        raise SystemExit(f"ABORT: expected exactly 1 match for '{label}', found {count}. No changes written.")
    content = content.replace(old, new)
    print(f"OK: patched '{label}'")


# "Print" (window.print()) already worked, but on a phone that means going
# through Share -> Print -> Save as PDF, which isn't obvious. These add two
# real, direct downloads instead: a PNG of just the plan image, and a PDF
# with the plan image plus the same materials list the print sheet builds
# (site areas, plants, sprinkler heads, zones/GPM, pipe footage, fixtures)
# -- using jsPDF (loaded in index.html) so no print dialog is involved.
apply(
    "document.getElementById('btn-design-print').addEventListener('click', () => {\n"
    "  if (!currentDesign) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => { buildPrintSheet(); window.print(); }, 150);\n"
    "});",
    "document.getElementById('btn-design-print').addEventListener('click', () => {\n"
    "  if (!currentDesign) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => { buildPrintSheet(); window.print(); }, 150);\n"
    "});\n"
    "\n"
    "function designFileBaseName() {\n"
    "  return (currentDesign.name || 'design').trim().replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '') || 'design';\n"
    "}\n"
    "\n"
    "document.getElementById('btn-design-download-png').addEventListener('click', () => {\n"
    "  if (!currentDesign || !stage) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => {\n"
    "    const a = document.createElement('a');\n"
    "    a.href = stage.toDataURL({ pixelRatio: 2 });\n"
    "    a.download = `${designFileBaseName()}.png`;\n"
    "    document.body.appendChild(a);\n"
    "    a.click();\n"
    "    a.remove();\n"
    "  }, 150);\n"
    "});\n"
    "\n"
    "document.getElementById('btn-design-download-pdf').addEventListener('click', () => {\n"
    "  if (!currentDesign || !stage) return;\n"
    "  deselect();\n"
    "  fitViewToContent();\n"
    "  setTimeout(() => {\n"
    "    const { jsPDF } = window.jspdf;\n"
    "    const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'letter' });\n"
    "    const pageW = doc.internal.pageSize.getWidth();\n"
    "    const pageH = doc.internal.pageSize.getHeight();\n"
    "    const margin = 36;\n"
    "\n"
    "    const linkBits = [];\n"
    "    if (currentDesign.customers && currentDesign.customers.name) linkBits.push(currentDesign.customers.name);\n"
    "    if (currentDesign.jobs && currentDesign.jobs.title) linkBits.push(currentDesign.jobs.title);\n"
    "\n"
    "    doc.setFontSize(18);\n"
    "    doc.text(currentDesign.name || 'Untitled design', margin, margin);\n"
    "    doc.setFontSize(10);\n"
    "    doc.setTextColor(90);\n"
    "    const metaLine = `${linkBits.length ? linkBits.join(' \\u2014 ') + '   ' : ''}Printed ${new Date().toLocaleDateString()}   Scale: 1 ft \\u2248 ${pxPerFt.toFixed(1)} px`;\n"
    "    doc.text(metaLine, margin, margin + 16);\n"
    "\n"
    "    const imgData = stage.toDataURL({ pixelRatio: 2 });\n"
    "    const imgProps = doc.getImageProperties(imgData);\n"
    "    const maxW = pageW - margin * 2;\n"
    "    const maxH = pageH - margin - 50;\n"
    "    let drawW = maxW;\n"
    "    let drawH = (imgProps.height / imgProps.width) * drawW;\n"
    "    if (drawH > maxH) {\n"
    "      drawH = maxH;\n"
    "      drawW = (imgProps.width / imgProps.height) * drawH;\n"
    "    }\n"
    "    doc.addImage(imgData, 'PNG', margin, margin + 30, drawW, drawH);\n"
    "\n"
    "    doc.addPage();\n"
    "    let y = margin;\n"
    "    doc.setTextColor(0);\n"
    "    function heading(text) {\n"
    "      if (y > pageH - margin - 20) { doc.addPage(); y = margin; }\n"
    "      doc.setFontSize(13);\n"
    "      doc.setFont(undefined, 'bold');\n"
    "      doc.text(text, margin, y);\n"
    "      y += 18;\n"
    "      doc.setFont(undefined, 'normal');\n"
    "      doc.setFontSize(10);\n"
    "    }\n"
    "    function row(label, value) {\n"
    "      if (y > pageH - margin) { doc.addPage(); y = margin; }\n"
    "      doc.text(String(label), margin, y);\n"
    "      doc.text(String(value), pageW - margin, y, { align: 'right' });\n"
    "      y += 14;\n"
    "    }\n"
    "\n"
    "    const plantCounts = new Map();\n"
    "    elements.filter((e) => e.type === 'plant').forEach((e) => plantCounts.set(e.plantKey, (plantCounts.get(e.plantKey) || 0) + 1));\n"
    "    const headEls = elements.filter((e) => e.type === 'head');\n"
    "    const headCounts = new Map();\n"
    "    headEls.forEach((e) => headCounts.set(e.headKey, (headCounts.get(e.headKey) || 0) + 1));\n"
    "    const zoneEls = elements.filter((e) => e.type === 'zone').sort((a, b) => a.zoneNumber - b.zoneNumber);\n"
    "    const pipeEls = elements.filter((e) => e.type === 'pipe');\n"
    "    const lateralFt = pipeEls.filter((e) => e.subtype === 'lateral').reduce((s, e) => s + polylineLengthFt(e.points), 0);\n"
    "    const mainlineFt = pipeEls.filter((e) => e.subtype === 'mainline').reduce((s, e) => s + polylineLengthFt(e.points), 0);\n"
    "    const fixtureCounts = new Map();\n"
    "    elements.filter((e) => e.type === 'fixture').forEach((e) => fixtureCounts.set(e.fixtureKey, (fixtureCounts.get(e.fixtureKey) || 0) + 1));\n"
    "    const areaTotals = {};\n"
    "    elements.filter((e) => e.type === 'area' && e.subtype !== 'boundary').forEach((e) => {\n"
    "      areaTotals[e.subtype] = (areaTotals[e.subtype] || 0) + polygonAreaSqFt(e.points);\n"
    "    });\n"
    "\n"
    "    heading('Site areas');\n"
    "    if (Object.keys(areaTotals).length === 0) row('No areas drawn', '');\n"
    "    for (const key of Object.keys(areaTotals)) {\n"
    "      const preset = CAT.AREA_PRESETS.find((p) => p.key === key);\n"
    "      row(preset ? preset.name : key, `${areaTotals[key].toFixed(0)} sq ft`);\n"
    "    }\n"
    "\n"
    "    if (plantCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Plants');\n"
    "      for (const [key, count] of plantCounts) {\n"
    "        const p = CAT.PLANT_CATALOG.find((x) => x.key === key);\n"
    "        row(p ? p.name : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (headCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Sprinkler heads');\n"
    "      for (const [key, count] of headCounts) {\n"
    "        const h = CAT.HEAD_CATALOG.find((x) => x.key === key);\n"
    "        row(h ? `${h.brand} ${h.model}` : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (zoneEls.length) {\n"
    "      y += 6;\n"
    "      heading('Zones');\n"
    "      for (const z of zoneEls) {\n"
    "        const heads = headEls.filter((h) => h.zoneNumber === z.zoneNumber);\n"
    "        const gpm = heads.reduce((s, h) => {\n"
    "          const h2 = CAT.HEAD_CATALOG.find((x) => x.key === h.headKey);\n"
    "          return s + (h2 ? h2.gpmFull : 0) * ((h.arc || 360) / 360);\n"
    "        }, 0);\n"
    "        row(`Zone ${z.zoneNumber}${z.label ? ` (${z.label})` : ''}`, `${heads.length} heads, ~${gpm.toFixed(1)} GPM`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (mainlineFt || lateralFt) {\n"
    "      y += 6;\n"
    "      heading('Pipe (approx.)');\n"
    "      row('Mainline', `${mainlineFt.toFixed(0)} ft`);\n"
    "      row('Lateral', `${lateralFt.toFixed(0)} ft`);\n"
    "    }\n"
    "\n"
    "    if (fixtureCounts.size) {\n"
    "      y += 6;\n"
    "      heading('Fixtures');\n"
    "      for (const [key, count] of fixtureCounts) {\n"
    "        const f = CAT.FIXTURE_CATALOG.find((x) => x.key === key);\n"
    "        row(f ? f.name : key, `x${count}`);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    doc.save(`${designFileBaseName()}.pdf`);\n"
    "  }, 150);\n"
    "});",
    "add Download PNG / Download PDF handlers",
)

path.write_text(content)
print("DONE: phone-app/design.js patched successfully.")
